import os

new_addendum = """
### **July 29, 2026 Addendum 8 — Orchestration, UI, Email & Decision Ledger**

**Objective**: Complete the operational integration and foundation of the PortfolioOS decision engine components to enable deterministic, non-ML decision-making, and create the final visualization and email deliverables.

**Actions**:
- **Weekly Portfolio Review Dashboard**: 
  - Created `frontend/src/WeeklyReviewDashboard.tsx` matching the design requirements.
  - Wired it into `App.tsx` routing (`/weeklyreview`) and sidebar navigation.
  - Displays Portfolio Health, Highest Priority Decision, Action Queue, and Holdings Status.
- **Weekly Review Email Automation**:
  - Created `send_weekly_portfolio_review` in `engine_core/email_service.py` to generate a plain HTML email using the exact JSON contract generated by `PortfolioOsReviewService`.
  - Sent and verified a live test email via AWS SES.
- **Decision Ledger Orchestration (Module 9)**:
  - Created `approve_weekly_review()` inside `PortfolioOsReviewService` which reads the generated actions and persists them into `cai_committee_decision` and `cai_decision_ledger`.
  - Created a new POST endpoint `/api/portfolio-review/v1/approve-weekly-review` in `api/portfolio_review.py`.
  - Hooked up the 'Approve & Record Actions' button in the React dashboard.

**Result**:
The system successfully integrates the deterministic analytical core with the visualization layer, email system, and decision tracking system, fully satisfying the July 29 PortfolioOS PRD.
"""

def fix_file(filepath):
    if not os.path.exists(filepath):
        return
    with open(filepath, 'r') as f:
        content = f.read()
    
    # The text I inserted started with "## 📅 Session: July 29, 2026 — PortfolioOS Operationalization"
    start_marker = "## 📅 Session: July 29, 2026 — PortfolioOS Operationalization & Decision Ledger Integration"
    end_marker = "Ingestion, Evaluation, and Decisioning (Dashboard + Email + Ledger) are fully integrated."
    
    if start_marker in content and end_marker in content:
        start_idx = content.find(start_marker)
        end_idx = content.find(end_marker) + len(end_marker)
        
        # Remove the block from the top
        clean_content = content[:start_idx] + content[end_idx:]
        clean_content = clean_content.lstrip() # clean up leading newlines
        
        # Append the new addendum to the bottom
        clean_content = clean_content.rstrip() + "\n\n" + new_addendum + "\n"
        
        with open(filepath, 'w') as f:
            f.write(clean_content)

fix_file('Sessions.md')
fix_file('Progress.md')
print("Logs fixed.")
