import pandas as pd
import numpy as np
import time

def run_minervini_research():
    print("Loading data...")
    start = time.time()
    df = pd.read_csv('backups/20260304/daily_prices.csv', parse_dates=['date'])
    print(f"Loaded {len(df)} rows in {time.time() - start:.2f}s")
    
    df = df.sort_values(['symbol', 'date'])
    
    print("Calculating rolling metrics...")
    if 'high' in df.columns and 'low' in df.columns:
        high_col, low_col = 'high', 'low'
    else:
        high_col, low_col = 'close', 'close'
        
    df['52w_high'] = df.groupby('symbol')[high_col].rolling(window=252, min_periods=126).max().reset_index(0, drop=True)
    df['52w_low'] = df.groupby('symbol')[low_col].rolling(window=252, min_periods=126).min().reset_index(0, drop=True)
    
    print("Filtering for target period...")
    df = df[(df['date'] >= '2024-01-01') & (df['date'] <= '2025-12-31')].copy()
    print(f"Filtered to {len(df)} rows for 2024-2025")
    
    cond_ema = (df['close'] > df['ema_50']) & (df['ema_50'] > df['ema_200'])
    cond_52w_low = df['close'] > (1.3 * df['52w_low'])
    cond_52w_high = df['close'] > (0.75 * df['52w_high'])
    
    df['passes_minervini'] = cond_ema & cond_52w_low & cond_52w_high
    
    scan_results = df[df['passes_minervini']]
    
    total_trading_days = df['date'].nunique()
    total_unique_stocks = scan_results['symbol'].nunique()
    
    passing_by_day = scan_results.groupby('date').size()
    avg_passing_per_day = passing_by_day.mean() if not passing_by_day.empty else 0
    max_passing_single_day = passing_by_day.max() if not passing_by_day.empty else 0
    
    print("\n" + "="*40)
    print("MINERVINI RESEARCH PROXY SCAN RESULTS")
    print("="*40)
    print(f"Total trading days analyzed: {total_trading_days}")
    print(f"Average number of stocks passing the scan per day: {avg_passing_per_day:.1f}")
    print(f"Total unique stocks that ever passed the scan: {total_unique_stocks}")
    print(f"The maximum number of stocks passing on a single day: {max_passing_single_day}")
    print("="*40)
    
    with open('MINERVINI_RESEARCH_FEASIBILITY.md', 'w') as f:
        f.write("# Minervini Research Feasibility\n\n")
        f.write("## Objective\n")
        f.write("Determine whether the core Minervini methodology can be reconstructed sufficiently from the available daily data to perform a research-only historical signal study.\n\n")
        f.write("## Methodology\n")
        f.write("The proxy scan applied the following filters over the period `2024-01-01` to `2025-12-31`:\n")
        f.write("1. `Price > EMA 50 > EMA 200`\n")
        f.write("2. `Price > 1.3 * 52W Low`\n")
        f.write("3. `Price > 0.75 * 52W High`\n\n")
        f.write("## Execution Summary\n")
        f.write(f"- **Total trading days analyzed:** {total_trading_days}\n")
        f.write(f"- **Average number of stocks passing per day:** {avg_passing_per_day:.1f}\n")
        f.write(f"- **Total unique stocks ever passing:** {total_unique_stocks}\n")
        f.write(f"- **Maximum passing on a single day:** {max_passing_single_day}\n\n")
        f.write("## Conclusion\n")
        f.write("Based on the number of historical signals generated by the proxy Minervini trend template, ")
        if avg_passing_per_day > 10:
            f.write("the core setup produces a meaningful and robust number of candidates. **Proceeding with proper data infrastructure and a full backtest is strongly justified.**\n")
        else:
            f.write("the core setup produces too few candidates historically. **Investing in proper data infrastructure may not be justified at this stage.**\n")

if __name__ == '__main__':
    run_minervini_research()
