import os

update_text = """
## 📅 Session: July 29, 2026 — PortfolioOS Operationalization & Decision Ledger Integration

**Session Start:** (afternoon IST)
**Session End:** (ongoing — awaiting commit)

### What Was Done This Session

#### 1. Weekly Portfolio Review Dashboard ✅
- Created `frontend/src/WeeklyReviewDashboard.tsx` matching the design requirements.
- Wired it into `App.tsx` routing (`/weeklyreview`) and sidebar navigation under CAI Workspace.
- Displays Portfolio Health, Highest Priority Decision, Action Queue, and Holdings Status.

#### 2. Weekly Review Email Automation ✅
- Created `send_weekly_portfolio_review` in `engine_core/email_service.py` to generate an HTML email.
- The email strictly uses the exact JSON contract generated by `PortfolioOsReviewService`.
- Successfully sent a live test email via AWS SES.

#### 3. Decision Ledger Orchestration (Final Goal) ✅
- Created `approve_weekly_review()` inside `PortfolioOsReviewService` which reads the generated actions and persists them into `cai_committee_decision` and `cai_decision_ledger`.
- Created a new POST endpoint `/api/portfolio-review/v1/approve-weekly-review` in `api/portfolio_review.py`.
- Hooked up the 'Approve & Record Actions' button in the React dashboard to formally stamp and persist the actions.
- Verified end-to-end ledger logging through a backend script.

### 📌 Current Milestone
- **PortfolioOS is completely operational!** 
- Ingestion, Evaluation, and Decisioning (Dashboard + Email + Ledger) are fully integrated.
"""

def prepend_to_file(filepath):
    if not os.path.exists(filepath):
        return
    with open(filepath, 'r') as f:
        content = f.read()
    
    with open(filepath, 'w') as f:
        f.write(update_text + "\n" + content)

prepend_to_file('Progress.md')
prepend_to_file('Sessions.md')
print("Logs updated successfully.")
